server:
  port: 5503
  host: localhost
auth:
  JWKS_URI: http://localhost:5501/well-known/jwks.json
database:
  url: mongodb+srv://vedant:vedant123@cluster0.mkzlnzg.mongodb.net/order?retryWrites=true&w=majority&appName=Cluster0
kafka:
  broker:
  - pkc-p11xm.us-east-1.aws.confluent.cloud:9092
  sasl:
    username: HZ3CVNFEXZPPXTO2
    password: cfltalgGPIPV2tIWmtH4GQWHy00kmyL1lqTTnVdzyBZbEO/n5AHI1LhrTQNF9dGg
razorPay:
  id: rzp_test_rPk76iyU7IhOOC
  secret: 86hxsT54F5deCImSj3Sz9BJE
webhook:
  secret: 47ia@dWW3fZpG4Za
frontend:
  clientUI: http://localhost:3000
  adminUI: http://localhost:5173
